name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  Production-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: "54.251.48.40"
          username: "root"
          password: "hulu007k"
          port: 22
          script: |
            /bin/bash -e /var/www/scripts/ServerManage.sh
